### ISSUE TITLE
Error: Git origin error

### ISSUE THREAD

**Issue by spederiva** [bahmutov/generator-node-bahmutov#34]
HI,

I just followed the instructions and get always the same error

```
$ git init
Initialized empty Git repository in /Users/sebastianp/Developer/Red-To/.git/
$ git remote add origin https://github.com/myuser/my-repository.git
$ DEBUG=gen yo node-bahmutov
using generator-node-bahmutov@1.25.0
  gen Copying .npmrc file +0ms
  gen Copying .gitignore file +4ms
  gen Looking for .git folder +1ms
  gen Getting Git origin url +0ms
  gen got remote origin url https://github.com/myuser/my-repository.git +2ms
Git origin error
Error: expected git@ remote url https://github.com/myuser/my-repository.git
    at lazyAssLogic (/usr/local/lib/node_modules/generator-node-bahmutov/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/usr/local/lib/node_modules/generator-node-bahmutov/node_modules/lazy-ass/index.js:115:28)
    at Object.getDomain (/usr/local/lib/node_modules/generator-node-bahmutov/app/https-remote-git-url.js:22:3)
    at originUrl.then (/usr/local/lib/node_modules/generator-node-bahmutov/app/index.js:70:40)
```

**Comment by bahmutov** [comment]
Ohh, I usually work with SSH git urls, thus it checked if the remote url started with `git@...` string, crashing on `https://` url. Need to add the support for this!
